const freeAgents = [
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Jonny Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Real Madrid",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "LB",
    type: "DEFENDER",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Juan",
    pos: "CDM",
    type: "MIDFIELDER",
    club: "FC Porto",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
  {
    name: "Roberto Carlos",
    pos: "ST",
    type: "FORWARD",
    club: "FC Barcelona",
  },
];

export default freeAgents;
