const players = [
  {
    name: "Lionel Messi",
    team: "Paris Saint Germain",
    kit: 30,
    image: "profilephoto",
    goals: 34,
    assists: 28,
    class: "superStar",
    //other info
    status: "not a free agent",
    awards: [
      "Ballon dor 2022",
      "Champions league 2012,2018,2022",
      "TOTW 24x",
      "World Cup 2022",
    ],
  },
  {
    name: "Neymar jr",
    team: "Paris Saint Germain",
    kit: 10,
    image: "profilephoto",
    goals: 28,
    assists: 26,
    class: "superStar",
    //other info
    status: "not a free agent",
    awards: ["Champions league 2022", "TOTS 3x"],
  },
  {
    name: "Kyllian Mbappe",
    team: "Paris Saint Germain",
    kit: 7,
    image: "profilephoto",
    goals: 45,
    assists: 12,
    class: "superStar",
    //other info
    status: "applied for free agency after season",
    awards: [],
  },
  {
    name: "Verrati",
    team: "Paris Saint Germain",
    kit: 6,
    image: "profilephoto",
    goals: 8,
    assists: 10,
    class: "star",
    //other info
    status: "not a free agent",
    awards: [],
  },
  {
    name: "Gueye",
    team: "Paris Saint Germain",
    kit: 23,
    image: "profilephoto",
    goals: 4,
    assists: 3,
    class: "elite",
    //other info
    status: "not a free agent",
    awards: [],
  },
  {
    name: "Cristiano Ronaldo",
    team: "Manchester United",
    kit: 7,
    image: "profilephoto",
    goals: 24,
    assists: 6,
    class: "superStar",
    //other info
    status: "not a free agent",
    awards: [],
  },
  {
    name: "Marcus Rashfod",
    team: "Manchester United",
    kit: 10,
    image: "profilephoto",
    goals: 24,
    assists: 16,
    class: "Star",
    //other info
    status: "not a free agent",
    awards: [],
  },
  {
    name: "McGuire",
    team: "Manchester United",
    kit: 4,
    image: "profilephoto",
    goals: 1,
    assists: 0,
    class: "regular",
    //other info
    status: "applied for free agency after season",
    awards: [],
  },
  {
    name: "Paul Pogba",
    team: "Manchester United",
    kit: 6,
    image: "profilephoto",
    goals: 8,
    assists: 20,
    class: "star",
    //other info
    status: "applied for free agency after season",
    awards: [],
  },
  {
    name: "Fred",
    team: "Manchester United",
    kit: 20,
    image: "profilephoto",
    goals: 6,
    assists: 3,
    class: "regular",
    //other info
    status: "not a free agent",
    awards: [],
  },
];
export default players;
