const transfers = [
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
  {
    id: 1,
    player: "Mathtam",
    from: "FC Barcelona",
    to: "PSG",
    type: "transfer",
  },
  {
    id: 2,
    player: "Ron",
    from: "Real Madrid",
    to: "Ajax",
    type: "transfer",
  },
  {
    id: 3,
    player: "Rickard",
    from: "West Ham",
    to: "Napoli",
    type: "Loan",
  },
  {
    id: 4,
    player: "Fred",
    from: "Manchester Utd",
    to: "Real Betis",
    type: "transfer",
  },
  {
    id: 5,
    player: "Hendrick",
    from: "Juventus",
    to: "Arsenal",
    type: "Loan",
  },
  {
    id: 6,
    player: "Fabregas",
    from: "Bayern Munich",
    to: "Everton",
    type: "Return",
  },
];

export default transfers;
